### ISSUE TITLE
LN Chaos/gimmick bug

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#12]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/54d3ba90-5fdb-4ad7-ba80-538a09abbffe)
Toy Musical 2 - Quad '99.27

**Comment by chown2** [comment]
How it looks in Toy Musical 3: https://youtu.be/bqu66U3jrGg?t=102
Looks fine to me, can you point at what exactly is wrong?

**Comment by BKVad1m** [comment]
> How it looks in Toy Musical 3: https://youtu.be/bqu66U3jrGg?t=102 Looks fine to me, can you point at what exactly is wrong?

TM 1-2 is pms, Toy Musical 3 is ENCRYPTED N9S charts.
https://tm2.toymusical.net/download.html

**Comment by chown2** [comment]
I tried it in LR2, and LRV renders it identically as far as I can tell. 
Can you show what is wrong on the screenshot/in the chart?

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/c4479dc8-0fc2-4c6e-a3a2-f0358605ade3)
3~7 LN together and glitches Tempo

**Comment by BKVad1m** [comment]
https://github.com/chown2/lunaticvibesf/assets/76803825/b93b3424-9cd8-477b-aa10-60de95093ddf

+ Mines 6~9 lane will now working

**Comment by BKVad1m** [comment]
> I tried it in LR2, and LRV renders it identically as far as I can tell. Can you show what is wrong on the screenshot/in the chart?

client itself
