### ISSUE TITLE
Some Stress Test fails [BMS OF (^^)]

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#13]
https://github.com/chown2/lunaticvibesf/assets/76803825/6072db3c-8dc5-43b6-98ec-b6f0dbcad242

**Comment by chown2** [comment]
Could you share the chart?

**Comment by BKVad1m** [comment]
> Could you share the chart?

https://1drv.ms/f/s!Ame8S9jJ12Unduqwx13LNSfyr-E There are downloaded packages from this

**Comment by BKVad1m** [comment]
[test.zip](https://github.com/chown2/lunaticvibesf/files/14895889/test.zip)
BPM Soft landing fails the test

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/1f339407-f440-418a-9f13-8f911b7b9bc7)

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/2dfd83a2-fe41-49d0-a8b3-1e537da411bf)
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/fee8ee0b-233b-4590-b523-6ef8bf728fdc)
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/321fb6bc-3d30-4a0c-b520-c92cd8a12308)

**Comment by chown2** [comment]
I don't have any of the charts mentioned. Can you try it with v0.13.4? https://github.com/chown2/lunaticvibesf/releases/tag/v0.13.4

**Comment by BKVad1m** [comment]
https://github.com/chown2/lunaticvibesf/issues/70

**Comment by BKVad1m** [comment]
@chown2 I just various charts have glitch and now will fixed
Triple A moment in 2nd stage class mode
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/0026392f-7b00-4c31-84b4-3d6ba5529818)
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/294bd48f-a169-4dd4-b9a9-e781b47d2047)
Let's go download BMS Packages at https://package.bms.ms

**Comment by chown2** [comment]
#70 should be fixed in v0.13.5 now. Are issues from here fixed now?

> Let's go download BMS Packages at https://package.bms.ms/

I'm limited on storage space and only keep table packages nowadays, as I only play those anyway, so I'd rather not download whole packages.
