### ISSUE TITLE
Load a "test.bms" for skin preview

### ISSUE THREAD

**Issue by Sonic-TV** [chown2/lunaticvibesf#130]
If no chart specified, the game will crash on skin select.

**Comment by chown2** [comment]
It's true that skin customize just shows whatever chart you are on in select, and as such there can be no chart, but the game should not crash from that. Do you get any messages about what's wrong as a dialogue window or in the log?

**Comment by Sonic-TV** [comment]
None.

**Comment by Sonic-TV** [comment]
Trigger this by going to the "DECIDE" tab, btw.
Play, select, result will simply says "no chart specified" on the console.

**Comment by chown2** [comment]
The crash might have been fixed in v0.18.0 by https://github.com/chown2/lunaticvibesf/commit/b4c8d6f6e80c8a6a3af93fd2aab1518df8e419cc
