### ISSUE TITLE
[Play] Support gauge after the dot number (beatoraja extension)

### ISSUE THREAD

**Issue by Sonic-TV** [chown2/lunaticvibesf#131]
Title, but Non-Hard gauge should be at 2.00% at least.
You can also add an option for displaying as 2%, 1%, 0.1% or 0.01% at minimum.

**Comment by chown2** [comment]
Is this about matching LR2 behavior health/scoring-wise or is this a request for new visual extension?

**Comment by Sonic-TV** [comment]
> Is this about matching LR2 behavior health/scoring-wise or is this a request for new visual extension?

Just a new visual extension.
fyi, the current gauge is displayed at 1% minimum.

**Comment by BKVad1m** [comment]
> Is this about matching LR2 behavior health/scoring-wise or is this a request for new visual extension?

This is matching not for LR2, a oraja series which number after dot is 407
