### ISSUE TITLE
Support for ISO keyboards

### ISSUE THREAD

**Issue by Marsoff9898** [chown2/lunaticvibesf#133]
Please implement support for ISO keyboards, especially on keys that ANSI don't have like the key between Z and the Left Shift.

Thank you.

**Comment by chown2** [comment]
What is the problem exactly? Does the key between Z and Left Shift not work? I don't think I have such a keyboard around so not sure how to reproduce that at the moment.

**Comment by Marsoff9898** [comment]
No. It doesn't work.

**Comment by chown2** [comment]
I found the issue present for NONUS_BACKSLASH and NONUS_HASH. Will upload the fix soon. Let me know if you encounter this with any other keys.
