### ISSUE TITLE
[BUG] Unknown Error when reading charts

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#137]
![image](https://github.com/user-attachments/assets/e8f36c73-88fb-446a-96bf-5b09799ba400)
`2024-11-23 12:29:14.980 ERROR [9896] ["asynclooper.cpp"@127] [AsyncLooper] UpdateLoop: Exception: unknown error`

https://github.com/user-attachments/assets/79037fad-203e-435d-9b66-597f58c0d165

**Comment by chown2** [comment]
Could you share the chart? There is no download link on LR2IR http://www.dream-pro.info/~lavalse/LR2IR/search.cgi?mode=ranking&bmsmd5=088c4411d7ce7e43c3d1933d21d033b6

**Comment by BKVad1m** [comment]
> Could you share the chart? There is no download link on LR2IR http://www.dream-pro.info/~lavalse/LR2IR/search.cgi?mode=ranking&bmsmd5=088c4411d7ce7e43c3d1933d21d033b6

@chown2 This is exclusive BOF:19 BMS package

**Comment by BKVad1m** [comment]
https://onedrive.live.com/?id=2765D7C9D84BBC67!118&cid=2765D7C9D84BBC67
https://1drv.ms/f/c/2765D7C9D84BBC67/Ame8S9jJ12UggCd2AAAAAAA?e=WPNg90

**Comment by BKVad1m** [comment]
Also happens in 0.18.0

**Comment by chown2** [comment]
Hm, this is link either requires a Microsoft account, which I have none, or is unavailable altogether. Are there any other mirrors?

**Comment by BKVad1m** [comment]
looks quietly fixed this issue with UTF-8 reason https://github.com/chown2/lunaticvibesf/commit/91445d43816b16365e7ee9be16312e635f886714

**Comment by chown2** [comment]
I wonder if there was Japanese in file extension in folder of that song. Anyway, thanks for checking!
