### ISSUE TITLE
Battle modes not working

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#138]

**Comment by BKVad1m** [comment]
```
+ bonus
```

https://github.com/Vad1mCSO2/BlackKnightMania_for_LV/commit/ed159c3807092a79e41efbe5945b966d833fbbc2 I optimized for 7K Left, Right and Battle mode

**Comment by chown2** [comment]
If you have other issues with battle, please also tell how it's supposed to work, as I haven't used this feature in LR2.
Right now starting replay with battle mode enabled doesn't work for example, I can make it do whatever but I'd rather match LR2.
