### ISSUE TITLE
Opening some folder that contains over 300 charts crash

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#16]
There's log in event viewer (Crash reporter no longer appears during crash)
```
Faulting application name: LunaticVibesF.exe, version: 0.0.0.0, time stamp: 0x66112804
Faulting module name: LunaticVibesF.exe, version: 0.0.0.0, time stamp: 0x66112804
Exception code: 0xc0000005
Fault offset: 0x00000000003523dd
Faulting process id: 0x1404
Faulting application start time: 0x01da883da7df3a32
Faulting application path: C:\Users\Administrator\Downloads\LR2 - HD (720p)\LR2 - HD (720p)\LR2beta3\LunaticVibesF.exe
Faulting module path: C:\Users\Administrator\Downloads\LR2 - HD (720p)\LR2 - HD (720p)\LR2beta3\LunaticVibesF.exe
Report Id: 35fb946d-84d5-4353-b5d8-b0408ed96a59
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by chown2** [comment]
There is a high chance this is the same as #10, which I just pushed a fix for. Can you try v0.12.3, please?
https://github.com/chown2/lunaticvibesf/releases/tag/v0.12.3

**Comment by BKVad1m** [comment]
> There is a high chance this is the same as #10, which I just pushed a fix for. Can you try v0.12.3, please? https://github.com/chown2/lunaticvibesf/releases/tag/v0.12.3

Freezing (Not responding) during startup

**Comment by chown2** [comment]
> Freezing (Not responding) during startup

Thanks for testing. I pushed a new release, can you check now, please?
https://github.com/chown2/lunaticvibesf/releases/tag/v0.12.5

**Comment by BKVad1m** [comment]
Quick spinning wheel on mouse wheel, open and up works fine.
Please add me tester in About menu

**Comment by chown2** [comment]
> Please add me tester in About menu

Sure, see ff1cce6d5e2fb3c65a5ad4400a86943e82ffe8ae :)
