### ISSUE TITLE
Wrong end of chart

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#19]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/e250d330-5122-4e9e-8691-db31e2772e0c)
♪ RYO - Ancient Stories II (Package of "98 BMS Packs/1999 - OLD BMS RANDOM COLLECTION") 
https://1drv.ms/f/s!Ame8S9jJ12Unduqwx13LNSfyr-E
In original version works fine

**Comment by chown2** [comment]
For posterity: this is https://github.com/chown2/lunaticvibesf/issues/23
