### ISSUE TITLE
Auto-scratch clears on result screen are shown as failed 

### ISSUE THREAD

**Issue by chown2** [chown2/lunaticvibesf#2]
Auto-scratch clears on result screen are shown as failed, yet they are saved as assist easy clears.

**Comment by chown2** [comment]
This check fails https://github.com/chown2/lunaticvibesf/blob/1cb697ac1335c81ed504bb39d8354d2dc2769a1b/src/game/ruleset/ruleset.h#L75
getNoteCount() does not account for disabled scratch notes. This also causes an issue with rank showing while playing.

**Comment by chown2** [comment]
Also likely related: in auto play with scratch assist the exscore will not be 100%, even though there will be no notes shown missed. Maybe happens outside of auto play too.

**Comment by BKVad1m** [comment]
I think LV skin references will be printing new options later
