### ISSUE TITLE
Tempo glitch

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#23]
https://github.com/chown2/lunaticvibesf/issues/13

**Comment by BKVad1m** [comment]
https://github.com/chown2/lunaticvibesf/issues/12

**Comment by BKVad1m** [comment]
Works ONLY pitch effector when set high speed

**Comment by BKVad1m** [comment]
This issue is very important to fix this

**Comment by BKVad1m** [comment]
Tempo, bars, judge timing, length goes glitching. In original LV no glitch

**Comment by chown2** [comment]
That was indeed a critical (and also Windows only :D) issue. Thank you for you patience.
https://github.com/chown2/lunaticvibesf/releases/tag/v0.13.4
