### ISSUE TITLE
Undeletable scores using /deletescore

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#27]
Before restart

https://github.com/chown2/lunaticvibesf/assets/76803825/98332c02-6136-4606-89a1-795ed98cd4a0

After restart
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/74cd4423-9d61-4bbc-ba0b-e89b18045723)

**Comment by chown2** [comment]
This can be worked-around by pressing "Rebuild score cache" under profile selection.
