### ISSUE TITLE
[Feature Request] LR2skin/LVskin/csv Skin Editor

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#31]
I'm very skilled LR2skin/LVskin/csv format. Created my skin using notepad++, paint.net, and Lunatic Vibes itself.
Skin editor contains interactive view to make this skin easily. 
LR2 16th years and no official source code due to hdd fault.

**Comment by chown2** [comment]
I'm definitely not going to work on this myself. PRs are welcome though, can reopen the issue if any appear.
