### ISSUE TITLE
Screenshot glitch bug

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#36]
![LV 2024-04-10 17-12-33](https://github.com/chown2/lunaticvibesf/assets/76803825/b169df01-1d25-48bb-afdb-d4b85cc82c5d)

**Comment by chown2** [comment]
The glitching itself doesn't seem to happen on Linux, I did find an issue with screenshot saving though, hopefully this was caused by it. Feel free to reopen if this happens again.
