### ISSUE TITLE
Disable BGA not working

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#45]
In LR2 disabling BGA working fine

**Comment by chown2** [comment]
As with search commands, I can't reproduce this on my end. Can you try with a fresh profile here too?

**Comment by chown2** [comment]
OK, I also got this.

**Comment by chown2** [comment]
Reproducing:
BGA ON
Enter a chart with picture BGA
BGA OFF
Open that chart, see the same BGA
Open any other chart, see the same BGA again

EDIT: that's what I did that day, but I can't reproduce it the same way anymore, and looking at the code, it seems even more strange.

**Comment by BKVad1m** [comment]
👌

**Comment by chown2** [comment]
I can't reproduce this anymore, perhaps the last commit helper with this. Feel free to reopen if it happens to you again, ideally with steps to reproduce.
