### ISSUE TITLE
Readme support in BMS chart (*.txt)

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#49]
This feature when created as help file but including multi-file text inside BMS charts

**Comment by chown2** [comment]
Lags while scrolling, need to make readme file searchin async
EDIT: it *is* async, but done while holding write-lock

**Comment by BKVad1m** [comment]
I think, add load delay after selecting song wheel

**Comment by BKVad1m** [comment]
In latest action build when scrolling too long and fps drops down to ~30 frame per seconds

**Comment by chown2** [comment]
> In latest action build when scrolling too long and fps drops down to ~30 frame per seconds

yep, that's what I referred to.
I made the 'open readme' button always shown for now, in v0.13.1 9740b7790688aa3854754545edea04ddf82fe6c4.
