### ISSUE TITLE
Song Database stuck in during refreshing

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#6]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/4cba2fc5-1a95-403f-aec3-1f9dea4fcafb)

**Comment by chown2** [comment]
Thanks for reporting, please, try v0.12.2.
https://github.com/chown2/lunaticvibesf/releases/tag/v0.12.2

It will not get stuck anymore, but songs will not get shown until song database is fully rebuilt, F8 won't be enough, so you will need to remove "gamedata/song.db" (it only contains song database cache, so you won't lose anything).

**Comment by BKVad1m** [comment]
> Thanks for reporting, please, try v0.12.2.
> https://github.com/chown2/lunaticvibesf/releases/tag/v0.12.2
> 
> It will not get stuck anymore, but songs will not get shown until song database is fully rebuilt, F8 won't be enough, so you will need to remove "gamedata/song.db" (it only contains song database cache, so you won't lose anything).

Thank you! I will trying
