### ISSUE TITLE
Git branch in about page is empty in CI builds

### ISSUE THREAD

**Issue by chown2** [chown2/lunaticvibesf#63]
![LV 2024-04-16 23-27-17](https://github.com/chown2/lunaticvibesf/assets/163607819/d95e6d16-fcae-4683-ac05-725b0245d3cc)

**Comment by BKVad1m** [comment]
What's skin? I don't have a skin.

**Comment by chown2** [comment]
@Vad1mCSO2 It's Vibe City by clarilotus https://www.youtube.com/watch?v=mpo4TNwomLw

**Comment by chown2** [comment]
GitHub actions: `fatal: No names found, cannot describe anything.`
