### ISSUE TITLE
Can't start the game with BMS path argument

### ISSUE THREAD

**Issue by chown2** [chown2/lunaticvibesf#65]
`./LunaticVibesF /path/to/file.bms` crashes:
```
runtime error: member access within null pointer of type 'const struct ScoreDB'
#3 .. ScoreDB::getScoreBMS(..) const /path/to/lunaticvibesf/src/db/db_score.cpp:75
#4 .. ScoreDB::getChartScoreBMS(..) const /path/to/lunaticvibesf/src/db/db_score.cpp:178
#5 .. ScenePlay::createRuleset() /path/to/lunaticvibesf/src/game/scene/scene_play.cpp:1000
#6 .. ScenePlay::ScenePlay() /path/to/lunaticvibesf/src/game/scene/scene_play.cpp:327
```

**Comment by BKVad1m** [comment]
Why? Linux

**Comment by BKVad1m** [comment]
Make a operating system label (e.g. Windows, Linux). I'm testing on Windows.

**Comment by chown2** [comment]
This issue has nothing to do with Linux specifically. Rather, if it worked on Windows, it's a Windows problem

> Make a operating system label

Most issues are not platform-specific, even if they only appear on one platform but not another. Different environments expose different underlying bugs.
