### ISSUE TITLE
[Enhancement] APNG Support

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#66]
https://apngasm.sourceforge.net This tool can assembly animated sprites and works in web browser

**Comment by chown2** [comment]
I'm not sure about usefulness of this, especially if other players don't support it.

**Comment by BKVad1m** [comment]
![Default animated](https://github.com/chown2/lunaticvibesf/assets/76803825/53443d8f-2fb2-4c7c-b041-15722abc0214)
This is test apng

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/9f7d02ad-412f-435d-999e-11378f82a974)
looks cursed

**Comment by chown2** [comment]
I might work on this eventually but not in the nearest future.
This would require implementing a new derivative of Texture that could switch images underneath, like TextureBmsBga does.

Also APNG specifically is not supported by SDL_image right now (by the library LVF loads images with)

https://github.com/libsdl-org/SDL_image/blob/b3c4c720cc65dfb3414752a79479dfe0db19eb0e/src/IMG.c#L82-L91
