### ISSUE TITLE
Add debug skin menus (F1-F8) to public builds

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#71]
How to use skin debug during developing new skin

**Comment by chown2** [comment]
Currently you need Debug build/development version of LVF to open these panels. I did not seriously use them myself, although I did think they may be useful to skin makers. I will add a way to enable them in public builds eventually.

**Comment by BKVad1m** [comment]
So, I'm skilled skin maker and making insane hyper customizable skin (e.g. Black Knight Mania skin [WIP])

**Comment by chown2** [comment]
Enable by clicking "Settings" while holding Shift. These settings do not persist between game restarts.

**Comment by BKVad1m** [comment]
during testing F6 to open text but screenshots when enable/disabled skin debug monitor

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/cb774640-4c0a-4b15-957a-c17ee177f35c)
Hidden text: Titles on song wheel

**Comment by BKVad1m** [comment]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/f2f14787-deae-45b4-9e2d-d5bfe9dffaab)
Feels like skin editor mode

**Comment by chown2** [comment]
> during testing F6 to open text but screenshots when enable/disabled skin debug monitor

This is just a debug tool, so I find that acceptable.

> Hidden text: Titles on song wheel

Those are LRV's internal values used for displaying song wheel texts. Please, don't reference them in your skins.

> Feels like skin editor mode

That's a demo window built in ImGui, it has some utilities useful for debugging some things.
