### ISSUE TITLE
False detection antivirus

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#73]
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/2d8c65ad-1759-46e3-a76e-f0812557cd70)

**Comment by chown2** [comment]
Curiously not a problem on VirusTotal
https://www.virustotal.com/gui/file/70da7505cb3ed71519ee412d05663b32c00b7611cf1bdeda37273d72bf69504b
https://www.virustotal.com/gui/file/0d4c50d488e11edb32b5c3ed9c48cb224ef3691dcad02cfb2a44ca49d569432b
Realistically I don't think there is anything I can do, perhaps next build won't trigger it.
The only potential benefactor I can imagine is digital signing, but as far as I know it requires buying a license which is basically an extortion scheme of Microsoft.  

Googling the "virus" name leads to another open source project with such issue: https://github.com/pyinstaller/pyinstaller/issues/5668
