### ISSUE TITLE
Custom skin resolution

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#75]
From LR1 and oraja series json. This feature including `#CUSTOMRESOLUTION,w,h` sets custom canvas resolution (e.g. 320x200/640x400 = DOS resolution, 3840x2160 = 4k and etc.)

**Comment by chown2** [comment]
Is `#RESOLUTION` not enough? Do any skin really use this?
Although, LRV does not support `#RESOLUTION 3` (2160p) beatoraja does, and does not handle invalid/unsupported values of it.

**Comment by BKVad1m** [comment]
Toy musical 3 uses 1024x768
![image](https://github.com/chown2/lunaticvibesf/assets/76803825/800cdd7d-d68e-48f2-9b21-9a0ec664ac2b)

**Comment by chown2** [comment]
`#CUSTOMRESOLUTION` is not a thing in Beatoraja as far as I can tell, so I'm will not support it right now as I'm not seeing usefulness and don't want to make own extensions. Will add #RESOLUTION 3 (4k/2160p) support though.

**Comment by BKVad1m** [comment]
Please update the readme that supports 4K

**Comment by chown2** [comment]
Done, thanks.

**Comment by BKVad1m** [comment]
![{C81C2297-D35B-483E-9360-58F67527A033}](https://github.com/user-attachments/assets/5e46505e-b440-4f18-8cef-95414a1605dd)
#SCREENSIZE was found in original Lunatic Rave
