### ISSUE TITLE
10k charts crash

### ISSUE THREAD

**Issue by BKVad1m** [chown2/lunaticvibesf#88]
https://github.com/chown2/lunaticvibesf/assets/76803825/13149866-c0e9-4082-bd99-096fef4fd3de

**Comment by BKVad1m** [comment]
[via Nokia 220] Reproducing: When I press the correct key, gets 11111 score but, no pgreat judge triggered. Meanwhile the blue note goes glitch and... TRIGS POOR JUDGE!!! Lunatic Vibes F has encounted an crash and logging into Event Viewer.

**Comment by chown2** [comment]
Thanks, I broke it in one of recent commits
